CREATE TABLE `d3totp` (
	`OXID` CHAR(32) NOT NULL,
	`OXUSERID` CHAR(32) NOT NULL,
	`USETOTP` TINYINT(1) NOT NULL DEFAULT '0',
	`SEED` VARCHAR(256) NOT NULL DEFAULT '0',
    `BC1` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #1',
    `BC2` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #2',
    `BC3` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #3',
    `BC4` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #4',
    `BC5` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #5',
    `BC6` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #6',
    `BC7` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #7',
    `BC8` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #8',
    `BC9` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #9',
    `BC10` VARCHAR(64) NOT NULL DEFAULT '0'  COMMENT 'BackupCode #10',
	PRIMARY KEY (`OXID`),
	UNIQUE INDEX `OXUSERID` (`OXUSERID`)
)
ENGINE=InnoDB
